### PR TITLE
Drop smart_proxy_dynflow PR test

### PR DESCRIPTION
**Pull request by ehelms**
I was reviewing https://github.com/theforeman/smart_proxy_dynflow/pull/123 and noticed at this point the smart_proxy_dynflow repository runs the same set of tests in Github Actions and Jenkins. I feel we can drop this duplication in Jenkins.

### CODE REVIEW

**Comment by ehelms** [comment]
@ekohl @evgeni Any objections to this change you can think of?

**Comment by ekohl** [comment]
The only thing I can think of is the weekly test we now run, but I'm not sure that adds any real value right now. https://ci.theforeman.org/job/smart-proxy-dynflow-test/

**Comment by ehelms** [comment]
I'm not convinced it does either, and it has low visibility. We could opt to run the Github Actions on a schedule if we wanted to achieve this same idea.

**Comment by ehelms** [comment]
Added a drop for the weekly test

**Comment by ehelms** [comment]
@ekohl give this another look?

**Review by ekohl — APPROVED** [review]

**Pull request merged**
