### PR TITLE
Use python3.11 on EL8 for package json filtering

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ianballou** [comment]
Just popping in to say this is required for us to release Katello 4.11.1

**Comment by evgeni** [comment]
Why don't we run this with whatever python3 is available?

**Comment by ehelms** [comment]
> Why don't we run this with whatever python3 is available?

*shrug* I just copied what we do here -- https://github.com/theforeman/jenkins-jobs/blob/8a5a5f9e46a7a807356c8c87c6033aa2ff43a323/theforeman.org/pipelines/lib/obal.groovy#L10

**Comment by evgeni** [comment]
Yeah, but that needs ansible-python, not any python ;)

**Pull request merged**
