### PR TITLE
Run obal with Python 3

### PR DESCRIPTION
**Pull request by ekohl**
Requires https://github.com/theforeman/foreman-infra/pull/1852

### CODE REVIEW

**Comment by ehelms** [comment]
Current issue I have seen:

```

[2023-07-13T00:24:38.244Z] + python3 -m obal lint rubygem-crass

[2023-07-13T00:24:38.244Z] Traceback (most recent call last):

[2023-07-13T00:24:38.244Z]   File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main

[2023-07-13T00:24:38.244Z]     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)

[2023-07-13T00:24:38.244Z]   File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details

[2023-07-13T00:24:38.244Z]     return _get_module_details(pkg_main_name, error)

[2023-07-13T00:24:38.244Z]   File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details

[2023-07-13T00:24:38.244Z]     __import__(pkg_name)

[2023-07-13T00:24:38.244Z]   File "/home/jenkins/workspace/foreman-packaging-rpm-copr-pr-test/obal/obal/__init__.py", line 11, in <module>

[2023-07-13T00:24:38.244Z]     import obsah

[2023-07-13T00:24:38.244Z]   File "/home/jenkins/workspace/foreman-packaging-rpm-copr-pr-test/obsah/obsah/__init__.py", line 19, in <module>

[2023-07-13T00:24:38.244Z]     import yaml

[2023-07-13T00:24:38.244Z] ModuleNotFoundError: No module named 'yaml'
```

**Comment by ekohl** [comment]
Thanks for testing. I'll update our Puppet manifest to ensure python3-yaml is installed.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-infra/pull/1854

**Comment by ehelms** [comment]
Guess we got to add a different Ansible version as well? Posting here until I have time to look at it.

```

[2023-07-13T15:54:34.444Z] + python3 -m obal lint rubygem-crass

[2023-07-13T15:54:34.545Z] Traceback (most recent call last):

[2023-07-13T15:54:34.545Z]   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main

[2023-07-13T15:54:34.545Z]     "__main__", mod_spec)

[2023-07-13T15:54:34.545Z]   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code

[2023-07-13T15:54:34.545Z]     exec(code, run_globals)

[2023-07-13T15:54:34.545Z]   File "/home/jenkins/workspace/foreman-packaging-rpm-copr-pr-test/obal/obal/__main__.py", line 5, in <module>

[2023-07-13T15:54:34.545Z]     main()

[2023-07-13T15:54:34.545Z]   File "/home/jenkins/workspace/foreman-packaging-rpm-copr-pr-test/obal/obal/__init__.py", line 70, in main

[2023-07-13T15:54:34.545Z]     obsah.main(cliargs=cliargs, application_config=application_config)

[2023-07-13T15:54:34.545Z]   File "/home/jenkins/workspace/foreman-packaging-rpm-copr-pr-test/obsah/obsah/__init__.py", line 360, in main

[2023-07-13T15:54:34.545Z]     from ansible.utils.display import Display # pylint: disable=all

[2023-07-13T15:54:34.545Z] ModuleNotFoundError: No module named 'ansible'

script returned exit code 1
```

**Comment by ekohl** [comment]
Oh yes, I guess ansible is used natively from Python rather than invoking `/usr/bin/ansible`. I'm starting to wonder if we should instead just spend time to migrate our nodes to EL8 or EL9.

**Comment by ehelms** [comment]
This is in a sense handled over here where we are using EL8 based Jenkins node for Copr work and having to use python3 obal -- https://github.com/theforeman/jenkins-jobs/pull/351/files#diff-5daa8883e6b581dfe840479a36f4a1f4268e083b50117189f8bff88d2b235556R10-R16

**Comment by evgeni** [comment]
given we have now el8 nodes, should this be just closed?

**Comment by ekohl** [comment]
Yes!

**Pull request closed without merging**
