### PR TITLE
drop pulpcore 3.13 jobs, nobody is using that branch

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — APPROVED** [review]
Thoughts about adding a README to https://yum.theforeman.org/pulpcore/3.13/ (and other "EOL" versions) that it's no longer maintained?

**Comment by evgeni** [comment]
> Thoughts about adding a README to https://yum.theforeman.org/pulpcore/3.13/ (and other "EOL" versions) that it's no longer maintained?

We don't have that for foreman and katello, why would pulpcore be different?

That said, we could implement something like that for all projects?

**Comment by ekohl** [comment]
The reason I asked was that with normal releases it's all linear. You know 2.4 & 2.5 are supported but everything older isn't. Here you have 3.11 & 3.14 supported, but 3.13 in between isn't. That surprising.

**Comment by evgeni** [comment]
Yes, but also these repos aren't supposed to be used outside of the Katello context, and Katello knows which repo to enable.

**Comment by ekohl** [comment]
Perhaps it's then sufficient to add a HEADER.html to https://yum.theforeman.org/pulpcore/ with that info.

**Comment by ekohl** [comment]
https://github.com/theforeman/foreman-infra/pull/1624 should do so.

**Pull request merged**
