### PR TITLE
Updates discovery jobs

### PR DESCRIPTION
**Pull request by lzap**
A bit late but better than never..

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Comment by lzap** [comment]
Thanks out of curiosity, when this gets applied? We have a PR against version 19.0-stable and its running tests against develop.

**Comment by ekohl** [comment]
https://ci.theforeman.org/job/jenkins-jobs-update/ and https://ci.theforeman.org/job/jenkins-jobs-update/178/ should have already applied this. Do you have a link to the PR?

**Comment by ehelms** [comment]
I think this updated the once things are merged job and not the PR job which is what @lzap you wanted. The PR job is defined here: https://github.com/theforeman/jenkins-jobs/blob/master/theforeman.org/yaml/jobs/foreman-plugins-pull-request.yaml#L9-L16

And as you can see is hard-coded to develop no matter what the branch is. For comparison, Katello uses a pipeline job where we can determine the proper checkout branch based on the input parameters: https://github.com/theforeman/jenkins-jobs/blob/master/theforeman.org/pipelines/test/testKatello.groovy#L1

I think maybe the best we could do is have a dedicated branch PR job based on the current design for plugins.

**Comment by lzap** [comment]
This is the PR: https://github.com/theforeman/foreman_discovery/pull/566

**Comment by evgeni** [comment]
This never worked Lukas, no.

What this PR did is to create the following job: https://ci.theforeman.org/job/test_plugin_foreman_discovery_20.0-stable/, that's the job that regularly tests 20.0-stable against 3.2-stable.

For PRs, https://ci.theforeman.org/job/foreman_discovery-pull-request/ is used, and that is configured in https://github.com/theforeman/jenkins-jobs/blob/master/theforeman.org/yaml/jobs/foreman-plugins-pull-request.yaml#L9-L16 to test only against develop, as it doesn't know anything about plugin specific mappings.

**Comment by lzap** [comment]
Still learning, still learning dude. I swear to God I thought we do cherry pick plugin PRs against stable branches.

**Comment by evgeni** [comment]
I wish.
You wish.
We all wish ;)

**Pull request merged**
