### PR TITLE
Add Apache license

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by evgeni** [comment]
Why Apache? Not that it matters too much, but an odd choice.

(are we positive all previous contributors are OK with that license?)

**Review by evgeni — APPROVED** [review]
I am good with this (re-)licensing!

**Comment by ehelms** [comment]
@theforeman/infrastructure-contributors @theforeman/infrastructure-maintainers Please review this addition of a LICENSE to the repository and add a Github approval if you are OK with the change.

**Review by melcorr — APPROVED** [review]

**Comment by ehelms** [comment]
I intend to merge one week from today.

https://github.com/orgs/theforeman/teams/infrastructure-contributors https://github.com/orgs/theforeman/teams/infrastructure-maintainers Please review this addition of a LICENSE to the repository and add a Github approval if you are OK with the change. Please reject if you have a concern and raise said concern for discussion.

**Pull request merged**
