### PR TITLE
stop testing nightly on centos 8

### PR DESCRIPTION
**Pull request by evgeni**
centos 8 is EOL and the repos will go away soon too

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Should it also be dropped from release pipelines since they'll disappear from mirrors?

**Comment by evgeni** [comment]
You mean stop defining the `pipeline-centos8` jobs? Yeah, could do that too.

**Review by ekohl — COMMENTED** [review]
A quick look through the code:
```console
$ rg centos8
centos.org/jobs/luna-pipelines.yml
11:      - centos8
12:      - centos8-stream
27:      - centos8-stream

centos.org/jobs/pulpcore-pipelines.yml
11:      - centos8

centos.org/jobs/katello-pipelines.yml
11:      - centos8
27:      - centos8
43:      - centos8
44:      - centos8-stream
60:      - centos8
61:      - centos8-stream

centos.org/jobs/foreman-pipelines.yml
9:      - centos8
10:      - centos8-stream
31:      - centos8
32:      - centos8-stream
51:      - centos8
52:      - centos8-stream

theforeman.org/pipelines/test/katello-pulpcore-integration.groovy
4:        'centos8'

theforeman.org/pipelines/vars/foreman/2.5.groovy
30:        'centos8',
31:        'centos8-stream',
35:        'centos8',

theforeman.org/pipelines/vars/foreman/3.1.groovy
28:        'centos8',
29:        'centos8-stream',
33:        'centos8',

theforeman.org/pipelines/vars/foreman/3.0.groovy
29:        'centos8',
30:        'centos8-stream',
34:        'centos8',

theforeman.org/pipelines/vars/foreman/nightly.groovy
31:        'centos8',
32:        'centos8-stream',
36:        'centos8-stream',

theforeman.org/pipelines/vars/katello/nightly.groovy
10:        'centos8',
11:        'centos8-stream',
15:        'centos8-stream',

theforeman.org/pipelines/vars/pulpcore/version.groovy
7:        'centos8'

theforeman.org/pipelines/vars/katello/4.1.groovy
10:        'centos8'
14:        'centos8'

theforeman.org/pipelines/vars/katello/4.2.groovy
10:        'centos8'
14:        'centos8'

theforeman.org/pipelines/vars/katello/4.3.groovy
10:        'centos8',
11:        'centos8-stream',
15:        'centos8',
```

Looks like there are also some places where we don't test on stream at all, like pulpcore and Katello 4.2. Are you planning to handle that as well?

**Comment by evgeni** [comment]
I am, but not as part of this PR.

**Review by ekohl — APPROVED** [review]

**Pull request merged**
